version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AUTH_SERVICE_URL=https://auth-service-production-efff.up.railway.app
      - AUCTION_SERVICE_URL=https://auction-service-production-0633.up.railway.app
      - BID_SERVICE_URL=https://bid-service-production.up.railway.app
    env_file:
      - .env
